### ISSUE TITLE
Gerber Files

### ISSUE THREAD

**Issue by Ratief** [TheRealFalseReality/aquapi#85]
**Is your feature request related to a problem? Please describe.**
It seems that the gerber files for the circuit board are missing. Is this project closed hardware?

**Describe the solution you'd like**
To have the gerber files added to the repo.

**Describe alternatives you've considered**

**Additional context**

**Comment by TheRealFalseReality** [comment]
Those I may not add as I somewhat consider the hardware proprietary. You are free create and use (not sell) your own boards using my design, but if I supply the manufacturing supplies, that's one step removed from someone creating their own boards to use. The software is open-sourced but the specific circuit-board is something I created for my product that I want to sell. I do sell the board ONLY for about $50 if you were interested.
